export const FILES = 'files'
export const IMAGES = 'images'
export const LISTS = '_lists'
export const INVITATIONS = '_invitations'
export const TAGS = '_tags'
export const TASKS = '_tasks'
export const USERS = '_users'
export const USERNAMES = '_usernames'
